// Diagnostic helper — writes messages to the on-page banner
function showDiag(message, isError = false) {
  const el = document.getElementById('diagnostic');
  if (!el) return;
  el.textContent = message;
  el.classList.toggle('error', !!isError);
}

// Global error handler so uncaught errors appear in the banner
window.onerror = function(message, source, lineno, colno, error) {
  const text = (error && error.message) ? error.message : message;
  showDiag('Runtime error: ' + text, true);
  console.error('Window.onerror:', message, source, lineno, colno, error);
  return false; // allow default handling too
};

// Chart initialization wrapped in try/catch so errors surface to the banner
(function initCharts() {
  try {
    if (typeof Chart === 'undefined') {
      throw new Error('Chart.js not loaded. Check your internet connection or the CDN.');
    }

    // --- Food Saved vs Wasted Chart ---
    const ctx1 = document.getElementById('foodTracker').getContext('2d');
    new Chart(ctx1, {
      type: 'doughnut',
      data: {
        labels: ['Food Saved', 'Food Wasted'],
        datasets: [{
          data: [65, 35], // placeholder values
          backgroundColor: ['#27ae60', '#e74c3c'],
          borderWidth: 1
        }]
      },
      options: {
        responsive: true,
        plugins: {
          legend: { position: 'bottom' },
          title: { display: true, text: 'Food Saved vs Wasted' }
        }
      }
    });

    // --- Recipes Generated Chart ---
    const ctx2 = document.getElementById('recipesTracker').getContext('2d');
    new Chart(ctx2, {
      type: 'bar',
      data: {
        labels: ['College Friendly', 'Vegan', 'Dairy Free', 'Mediterranean'],
        datasets: [{
          label: 'Recipes Generated',
          data: [12, 7, 5, 9], // placeholder values
          backgroundColor: '#3498db'
        }]
      },
      options: {
        responsive: true,
        plugins: {
          legend: { display: false },
          title: { display: true, text: 'Recipes Generated by Category' }
        },
        scales: { y: { beginAtZero: true } }
      }
    });

    showDiag('Charts rendered successfully', false);
  } catch (err) {
    console.error('Chart init error:', err);
    showDiag('Error initializing charts: ' + (err.message || err), true);
  }
})();
